apiVersion: v1
kind: Service
metadata:
  name: kubectl-proxy
  labels:
    component: kubectl-proxy
spec:
  selector:
    component: kubectl-proxy
  ports:
  - name: kubectl-proxy
    port: 8080
    protocol: TCP
