apiVersion: v1
kind: ReplicationController
metadata:
  name: kubectl-proxy
spec:
  selector:
    component: kubectl-proxy
  template:
    metadata:
      labels:
        component: kubectl-proxy
    spec:
      containers:
      - name: kubectl-proxy
        image: samnco/docker-kubectl-proxy
        env:
        - name: PORT
          value: 8080
        - name: APISERVER
          value: http://your.kubectl-api-server-endpoint
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: proxy
          protocol: TCP